"""Agentic development capability inventory for CHP."""

from __future__ import annotations

from .types import JSON

AGENTIC_DEVELOPMENT_CAPABILITIES: list[JSON] = [
    {
        "id": "trace_execution",
        "status": "implemented",
        "category": "execution-evidence",
        "priority": "p0",
        "purpose": "Capture and correlate execution events from agents, tools, or systems.",
        "inputs": ["source", "event_type", "timestamp", "correlation_hints"],
        "evidence": ["execution_started", "trace_event_accepted", "execution_completed"],
        "development_value": "Gives agent and tool work a structured execution record instead of relying on terminal scrollback.",
    },
    {
        "id": "explain_execution",
        "status": "implemented",
        "category": "execution-evidence",
        "priority": "p0",
        "purpose": "Produce an evidence-backed explanation of a trace.",
        "inputs": ["correlation_id"],
        "evidence": ["execution_started", "execution_completed", "execution_failed"],
        "development_value": "Turns raw evidence into a readable account of what happened, separating facts from inferences.",
    },
    {
        "id": "evaluate_counterfactual",
        "status": "implemented",
        "category": "governance-readiness",
        "priority": "p0",
        "purpose": "Evaluate proposed constraints against an observed trace.",
        "inputs": ["correlation_id", "proposed_invariants"],
        "evidence": ["execution_started", "execution_completed", "execution_failed"],
        "development_value": "Lets the team test future governance rules against real work before enforcing them.",
    },
    {
        "id": "codex.record_decision",
        "status": "implemented",
        "category": "self-observation",
        "priority": "p0",
        "purpose": "Record task intent, changed files, commands, tests, outcome, open questions, and follow-up actions.",
        "inputs": ["task_intent", "files_inspected", "files_changed", "commands_run", "tests_run", "outcome"],
        "evidence": ["execution_started", "codex_action_recorded", "execution_completed"],
        "development_value": "Creates a durable work trace for the engineering agent building CHP.",
    },
    {
        "id": "chp.check_schema_spec_alignment",
        "status": "implemented",
        "category": "protocol-quality",
        "priority": "p0",
        "purpose": "Check v0.1 spec, schemas, Python models, and TypeScript types for drift.",
        "inputs": ["repo_root"],
        "evidence": ["execution_started", "schema_spec_alignment_checked", "execution_completed"],
        "development_value": "Keeps the public protocol vocabulary stable across docs and implementations.",
    },
    {
        "id": "chp.check_launch_messaging",
        "status": "implemented",
        "category": "launch-quality",
        "priority": "p0",
        "purpose": "Check public docs for evidence-first positioning and overclaim drift.",
        "inputs": ["repo_root"],
        "evidence": ["execution_started", "launch_messaging_checked", "execution_completed"],
        "development_value": "Prevents CHP from drifting into MCP replacement or enterprise-governance claims before v0.1 is ready.",
    },
    {
        "id": "chp.inventory_agentic_capabilities",
        "status": "implemented",
        "category": "development-feedback-loop",
        "priority": "p0",
        "purpose": "Return the current and planned capability inventory for agentic development.",
        "inputs": ["include_planned"],
        "evidence": ["execution_started", "agentic_capability_inventory_generated", "execution_completed"],
        "development_value": "Makes CHP's own development roadmap discoverable through CHP execution evidence.",
    },
    {
        "id": "chp.audit_evidence_quality",
        "status": "implemented",
        "category": "protocol-quality",
        "priority": "p1",
        "purpose": "Score traces for correlation, outcome consistency, failure visibility, denial visibility, and redaction safety.",
        "inputs": ["correlation_id"],
        "evidence": ["execution_started", "evidence_quality_audited", "execution_completed"],
        "development_value": "Answers whether a trace is actually useful enough to support debugging, review, and governance readiness.",
    },
    {
        "id": "chp.run_conformance_matrix",
        "status": "implemented",
        "category": "protocol-quality",
        "priority": "p1",
        "purpose": "Run conformance against the local host, HTTP-served host, sample passing host, and sample failing cases.",
        "inputs": ["repo_root", "targets", "timeout_seconds"],
        "evidence": ["execution_started", "conformance_matrix_completed", "execution_completed", "execution_failed"],
        "development_value": "Turns protocol compatibility into repeatable evidence rather than an assertion.",
    },
    {
        "id": "chp.check_catalog_alignment",
        "status": "planned",
        "category": "protocol-quality",
        "priority": "p1",
        "purpose": "Check roadmap, inventory, contracts, and examples against the CHP capability catalog.",
        "inputs": ["repo_root", "catalog_path"],
        "evidence": ["execution_started", "catalog_alignment_checked", "execution_completed", "execution_failed"],
        "development_value": "Prevents the broad catalog from drifting away from the executable protocol roadmap.",
    },
    {
        "id": "chp.validate_capability_contract",
        "status": "planned",
        "category": "developer-lifecycle",
        "priority": "p1",
        "purpose": "Validate capability contract files against the catalog-derived contract template.",
        "inputs": ["contract_path"],
        "evidence": ["execution_started", "capability_contract_validated", "execution_completed", "execution_failed"],
        "development_value": "Lets capability authors check contract completeness before adding runtime complexity.",
    },
    {
        "id": "chp.assess_capability_maturity",
        "status": "planned",
        "category": "developer-lifecycle",
        "priority": "p1",
        "purpose": "Assess a capability against the catalog maturity levels.",
        "inputs": ["capability_id", "contract_path"],
        "evidence": ["execution_started", "capability_maturity_assessed", "execution_completed", "execution_failed"],
        "development_value": "Turns the catalog maturity model into an actionable release gate.",
    },
    {
        "id": "chp.version_control.inspect_repo",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p1",
        "purpose": "Inspect local Git repository identity, branch, status, remotes, and Radicle hints.",
        "inputs": ["repo_root"],
        "evidence": ["execution_started", "version_control_repo_inspected", "execution_completed"],
        "development_value": "Makes the repository state part of the same evidence loop as code changes and checks.",
    },
    {
        "id": "chp.version_control.diff_summary",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p1",
        "purpose": "Summarize local Git changes without storing full patch content by default.",
        "inputs": ["repo_root", "include_patch"],
        "evidence": ["execution_started", "version_control_diff_summarized", "execution_completed"],
        "development_value": "Lets agents and reviewers reason about change scope without leaking entire diffs into evidence.",
    },
    {
        "id": "chp.version_control.precommit_check",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p1",
        "purpose": "Run configured local pre-commit checks and record structured evidence.",
        "inputs": ["repo_root", "checks", "timeout_seconds"],
        "evidence": ["execution_started", "version_control_precommit_checked", "execution_completed"],
        "development_value": "Connects tests and checks to the capability evidence trail before a commit or patch is proposed.",
    },
    {
        "id": "chp.version_control.release_evidence_bundle",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p1",
        "purpose": "Generate a local version-control release evidence bundle.",
        "inputs": ["repo_root", "checks", "work_correlation_ids"],
        "evidence": ["execution_started", "version_control_release_bundle_generated", "execution_completed"],
        "development_value": "Collects repository state, diff summary, checks, and work traces into one local release record.",
    },
    {
        "id": "chp.radicle.identity",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Inspect local Radicle identity through the rad CLI.",
        "inputs": ["repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_identity_inspected", "execution_completed", "execution_failed"],
        "development_value": "Prepares decentralized version-control identity to participate in CHP evidence.",
    },
    {
        "id": "chp.radicle.repo_status",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Inspect local Radicle repository status through the rad CLI.",
        "inputs": ["repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_repo_status_inspected", "execution_completed", "execution_failed"],
        "development_value": "Makes decentralized repository status visible before patch operations are attempted.",
    },
    {
        "id": "chp.radicle.patches.list",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "List Radicle patches through a guarded CHP capability.",
        "inputs": ["state", "repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_patches_listed", "execution_completed", "execution_failed"],
        "development_value": "Lets agents discover pending Radicle work without leaving the CHP evidence boundary.",
    },
    {
        "id": "chp.radicle.patches.inspect",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Inspect a Radicle patch through a guarded CHP capability.",
        "inputs": ["patch_id", "repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_patch_inspected", "execution_completed", "execution_failed"],
        "development_value": "Makes Radicle patch review evidence-addressable before merge automation is introduced.",
    },
    {
        "id": "chp.radicle.patches.comment",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Comment on a Radicle patch only when explicit mutation approval is present.",
        "inputs": ["patch_id", "body", "allow_mutation", "repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_patch_commented", "execution_completed", "execution_denied", "execution_failed"],
        "development_value": "Provides a guarded path for attaching CHP evidence back to decentralized review.",
    },
    {
        "id": "chp.radicle.patches.merge_dry_run",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Dry-run a Radicle patch merge through a guarded CHP capability.",
        "inputs": ["patch_id", "revision", "repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_patch_merge_checked", "execution_completed", "execution_failed"],
        "development_value": "Allows merge readiness to be evidenced before any mutating operation is allowed.",
    },
    {
        "id": "chp.radicle.patches.merge",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p2",
        "purpose": "Merge a Radicle patch only when explicit mutation approval is present.",
        "inputs": ["patch_id", "revision", "allow_mutation", "repo_root", "rad_path"],
        "evidence": ["execution_started", "radicle_patch_merged", "execution_completed", "execution_denied", "execution_failed"],
        "development_value": "Creates the semantic slot for governed decentralized merge operations.",
    },
    {
        "id": "chp.version_control.verify_merge_readiness",
        "status": "implemented",
        "category": "version-control-governance",
        "priority": "p1",
        "purpose": "Verify release evidence, conformance, checks, and approval before merge.",
        "inputs": ["repo_root", "checks", "work_correlation_ids", "release_correlation_id", "approval"],
        "evidence": ["execution_started", "version_control_merge_readiness_verified", "execution_completed", "execution_failed"],
        "development_value": "Turns version-control governance from observation into a pre-merge decision boundary.",
    },
    {
        "id": "chp.compare_runs",
        "status": "planned",
        "category": "development-intelligence",
        "priority": "p1",
        "purpose": "Compare two work traces for changed files, commands, test deltas, failures, and evidence coverage.",
        "inputs": ["left_correlation_id", "right_correlation_id"],
        "evidence": ["execution_started", "work_runs_compared", "execution_completed"],
        "development_value": "Helps explain what changed between attempts and whether a fix actually improved the evidence.",
    },
    {
        "id": "chp.propose_next_issue",
        "status": "planned",
        "category": "development-intelligence",
        "priority": "p1",
        "purpose": "Propose follow-up issues from recent evidence, failed checks, TODOs, and repeated manual work.",
        "inputs": ["correlation_ids", "repo_root"],
        "evidence": ["execution_started", "next_issue_proposed", "execution_completed"],
        "development_value": "Closes the loop from observed engineering work to actionable backlog items.",
    },
    {
        "id": "chp.wrap_tool_call",
        "status": "planned",
        "category": "agent-tooling",
        "priority": "p1",
        "purpose": "Wrap an arbitrary local tool call with a CHP invocation envelope and evidence emission.",
        "inputs": ["tool_name", "payload", "subject", "correlation_id"],
        "evidence": ["execution_started", "tool_call_observed", "execution_completed", "execution_failed"],
        "development_value": "Makes ordinary agent tool calls visible without requiring those tools to become CHP-native first.",
    },
    {
        "id": "chp.inspect_repository",
        "status": "planned",
        "category": "repository-intelligence",
        "priority": "p2",
        "purpose": "Collect repository structure, protocol assets, package metadata, tests, and known launch files.",
        "inputs": ["repo_root"],
        "evidence": ["execution_started", "repository_inspected", "execution_completed"],
        "development_value": "Gives future engineering agents a consistent context-gathering entry point.",
    },
    {
        "id": "chp.redact_evidence_payload",
        "status": "planned",
        "category": "trust-and-safety",
        "priority": "p2",
        "purpose": "Apply local redaction policies to evidence payloads before export or sharing.",
        "inputs": ["event", "policy"],
        "evidence": ["execution_started", "evidence_payload_redacted", "execution_completed"],
        "development_value": "Keeps evidence useful without normalizing accidental secret or sensitive payload leakage.",
    },
]


def build_agentic_capability_inventory(*, include_planned: bool = True) -> JSON:
    capabilities = [
        capability
        for capability in AGENTIC_DEVELOPMENT_CAPABILITIES
        if include_planned or capability["status"] == "implemented"
    ]
    categories = sorted({str(capability["category"]) for capability in capabilities})
    status_counts: dict[str, int] = {}
    priority_counts: dict[str, int] = {}
    for capability in capabilities:
        status = str(capability["status"])
        priority = str(capability["priority"])
        status_counts[status] = status_counts.get(status, 0) + 1
        priority_counts[priority] = priority_counts.get(priority, 0) + 1

    return {
        "purpose": "Inventory CHP capabilities that make agentic development visible, replayable, and ready for governance.",
        "capability_count": len(capabilities),
        "categories": categories,
        "status_counts": status_counts,
        "priority_counts": priority_counts,
        "capabilities": capabilities,
        "recommended_next": [
            "chp.check_catalog_alignment",
            "chp.validate_capability_contract",
            "chp.wrap_tool_call",
        ],
    }
