/**
 * CHP reserved names — GENERATED by scripts/gen-reserved-names.py from
 * the reference source (chp_core/types.py). Do not edit by hand; the
 * `ts_reserved_names_current` alignment guard rejects drift.
 *
 * These are the names an implementation MUST NOT redefine
 * (spec/reserved-names.md, chp-governance-v0.2.md section 5).
 */

export const RESERVED_DENIAL_CODES = [
  "approval_required",
  "budget_exceeded",
  "capability_disabled",
  "capability_not_found",
  "capability_version_unsupported",
  "host_unreachable",
  "input_schema_validation_failed",
  "invariant_failed",
  "mandate_exhausted",
  "mandate_invalid",
  "policy_blocked",
  "safety_blocked",
  "unsupported_mode",
  "version_unsupported",
] as const;

export type ReservedDenialCode = (typeof RESERVED_DENIAL_CODES)[number];

export const AUTONOMY_EVIDENCE_TYPES = [
  "approval_denied",
  "approval_granted",
  "approval_requested",
  "budget_exceeded",
] as const;

export const COGNITION_EVIDENCE_TYPES = [
  "delegation_accepted",
  "delegation_completed",
  "delegation_created",
  "delegation_reassigned",
  "delegation_rejected",
  "memory_deleted",
  "memory_read",
  "memory_written",
  "outcome_scored",
  "plan_completed",
  "plan_created",
  "plan_failed",
  "plan_revised",
  "plan_step_completed",
  "plan_step_started",
  "reflection_completed",
  "reflection_started",
] as const;

export const COMPLIANCE_EVIDENCE_TYPES = [
  "compliance_report_generated",
  "evidence_purged",
  "evidence_redacted",
  "retention_policy_applied",
] as const;

export const CORE_EVIDENCE_TYPES = [
  "execution_completed",
  "execution_denied",
  "execution_failed",
  "execution_skipped",
  "execution_started",
] as const;

export const DOMAIN_EVENT_EVIDENCE_TYPES = [
  "domain_event_emitted",
  "domain_event_operation_failed",
  "domain_events_queried",
] as const;

export const FEDERATION_EVIDENCE_TYPES = [
  "task_participants_declared",
] as const;

export const GRAPH_EVIDENCE_TYPES = [
  "graph_entity_added",
  "graph_operation_failed",
  "graph_queried",
  "graph_relation_added",
  "graph_traversed",
] as const;

export const IDENTITY_EVIDENCE_TYPES = [
  "identity_anchored",
  "key_generated",
  "key_revoked",
  "key_rotated",
] as const;

export const INCIDENT_EVIDENCE_TYPES = [
  "incident_closed",
  "incident_escalated",
  "incident_opened",
  "incident_remediation_applied",
  "incident_resolved",
  "incident_trigger_fired",
] as const;

export const INGESTION_EVIDENCE_TYPES = [
  "ingestion_completed",
  "ingestion_failed",
  "ingestion_started",
] as const;

export const METRICS_EVIDENCE_TYPES = [
  "execution_completed",
  "execution_denied",
  "execution_failed",
  "execution_started",
] as const;

export const RETRIEVAL_EVIDENCE_TYPES = [
  "retrieval_completed",
  "retrieval_failed",
  "retrieval_started",
] as const;

export const ROUTING_EVIDENCE_TYPES = [
  "host_marked_healthy",
  "host_marked_unhealthy",
] as const;

export const SAFETY_EVIDENCE_TYPES = [
  "safety_action_approved",
  "safety_action_blocked",
  "safety_assessment_completed",
  "safety_assessment_started",
  "safety_guardrail_triggered",
] as const;

export const SESSION_EVIDENCE_TYPES = [
  "agent_session_completed",
  "agent_session_resumed",
  "agent_session_started",
] as const;

export const STATE_MACHINE_EVIDENCE_TYPES = [
  "state_machine_blocked",
  "state_machine_cancelled",
  "state_machine_completed",
  "state_machine_created",
  "state_machine_failed",
  "state_machine_transition_completed",
  "state_machine_transition_started",
] as const;

export const SUPPLY_CHAIN_EVIDENCE_TYPES = [
  "host_adapter_install_rejected",
  "host_adapter_installed",
] as const;

export const TRANSFORMATION_EVIDENCE_TYPES = [
  "transformation_completed",
  "transformation_failed",
  "transformation_started",
] as const;

export const VERSION_CONTROL_EVIDENCE_TYPES = [
  "rc_tag_pushed",
  "release_tag_pushed",
  "version_bumped",
  "version_control_diff_summarized",
  "version_control_merge_readiness_verified",
  "version_control_precommit_checked",
  "version_control_release_bundle_generated",
  "version_control_repo_inspected",
] as const;

export const WORKFLOW_EVIDENCE_TYPES = [
  "workflow_completed",
  "workflow_failed",
  "workflow_started",
  "workflow_step_completed",
  "workflow_step_failed",
  "workflow_step_started",
] as const;

export const ALL_RESERVED_EVIDENCE_TYPES = [
  ...AUTONOMY_EVIDENCE_TYPES,
  ...COGNITION_EVIDENCE_TYPES,
  ...COMPLIANCE_EVIDENCE_TYPES,
  ...CORE_EVIDENCE_TYPES,
  ...DOMAIN_EVENT_EVIDENCE_TYPES,
  ...FEDERATION_EVIDENCE_TYPES,
  ...GRAPH_EVIDENCE_TYPES,
  ...IDENTITY_EVIDENCE_TYPES,
  ...INCIDENT_EVIDENCE_TYPES,
  ...INGESTION_EVIDENCE_TYPES,
  ...METRICS_EVIDENCE_TYPES,
  ...RETRIEVAL_EVIDENCE_TYPES,
  ...ROUTING_EVIDENCE_TYPES,
  ...SAFETY_EVIDENCE_TYPES,
  ...SESSION_EVIDENCE_TYPES,
  ...STATE_MACHINE_EVIDENCE_TYPES,
  ...SUPPLY_CHAIN_EVIDENCE_TYPES,
  ...TRANSFORMATION_EVIDENCE_TYPES,
  ...VERSION_CONTROL_EVIDENCE_TYPES,
  ...WORKFLOW_EVIDENCE_TYPES,
] as const;
