"""Tests for PlanningAdapter.

All tests are stateless — no subprocess or external backend required.
"""
from __future__ import annotations

import pytest
from chp_core import LocalCapabilityHost, register_adapter
from chp_core.store import SQLiteEvidenceStore

from chp_adapter_planning import PlanningAdapter, PlanningConfig


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_host() -> LocalCapabilityHost:
    adapter = PlanningAdapter()
    host = LocalCapabilityHost(store=SQLiteEvidenceStore(":memory:"))
    register_adapter(host, adapter)
    return host


def _events(host: LocalCapabilityHost) -> list[dict]:
    return [e for e in host.store.all() if "capability_uri" not in e.get("payload", {})]


def _event_types(host: LocalCapabilityHost) -> list[str]:
    return [e["event_type"] for e in _events(host)]


# ---------------------------------------------------------------------------
# Capability registration
# ---------------------------------------------------------------------------

class TestRegistration:
    async def test_four_capabilities_registered(self):
        host = _make_host()
        # keys are "id:version" — check id prefix
        keys = " ".join(host._capabilities.keys())
        assert "chp.adapters.planning.create_plan" in keys
        assert "chp.adapters.planning.step_update" in keys
        assert "chp.adapters.planning.revise" in keys
        assert "chp.adapters.planning.reflect" in keys


# ---------------------------------------------------------------------------
# create_plan
# ---------------------------------------------------------------------------

class TestCreatePlan:
    async def test_success(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "implement Tier 3 adapters",
            "steps": [
                {"step_id": "s1", "description": "write planning adapter"},
                {"step_id": "s2", "description": "write delegation adapter"},
            ],
        })
        assert result.outcome == "success"
        assert result.data["intent"] == "implement Tier 3 adapters"
        assert len(result.data["steps"]) == 2

    async def test_autogenerated_plan_id(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "do something",
        })
        assert result.outcome == "success"
        assert result.data["plan_id"].startswith("plan_")

    async def test_explicit_plan_id_preserved(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "plan_id": "my-plan-001",
            "intent": "do something",
        })
        assert result.data["plan_id"] == "my-plan-001"

    async def test_emits_plan_created(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "do something",
            "steps": [{"step_id": "a", "description": "first step"}],
        })
        types = _event_types(host)
        assert "plan_created" in types

    async def test_plan_created_contains_step_count(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "x",
            "steps": [
                {"step_id": "s1", "description": "d1"},
                {"step_id": "s2", "description": "d2"},
                {"step_id": "s3", "description": "d3"},
            ],
        })
        ev = next(e for e in _events(host) if e["event_type"] == "plan_created")
        assert ev["payload"]["step_count"] == 3

    async def test_no_steps_allowed(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "minimal plan",
        })
        assert result.outcome == "success"
        assert result.data["steps"] == []

    async def test_missing_intent_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {})
        assert result.outcome == "denied"

    async def test_unknown_field_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "x",
            "bogus": True,
        })
        assert result.outcome == "denied"

    async def test_parent_correlation_id_round_trips(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.create_plan", {
            "intent": "child plan",
            "parent_correlation_id": "corr_abc123",
        })
        assert result.data["parent_correlation_id"] == "corr_abc123"


# ---------------------------------------------------------------------------
# step_update
# ---------------------------------------------------------------------------

class TestStepUpdate:
    async def test_started_emits_plan_step_started(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.step_update", {
            "plan_id": "p1",
            "step_id": "s1",
            "status": "started",
        })
        assert result.outcome == "success"
        assert "plan_step_started" in _event_types(host)

    async def test_completed_emits_plan_step_completed(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.step_update", {
            "plan_id": "p1",
            "step_id": "s1",
            "status": "completed",
            "result": {"files_written": 3},
        })
        types = _event_types(host)
        assert "plan_step_started" not in types
        assert "plan_step_completed" in types

    async def test_failed_emits_plan_step_completed_with_error(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.step_update", {
            "plan_id": "p1",
            "step_id": "s1",
            "status": "failed",
            "error": "subprocess exited 1",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "plan_step_completed")
        assert ev["payload"]["status"] == "failed"
        assert ev["payload"]["error"] == "subprocess exited 1"

    async def test_returns_ids_and_status(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.step_update", {
            "plan_id": "p1", "step_id": "s2", "status": "completed",
        })
        assert result.data == {"plan_id": "p1", "step_id": "s2", "status": "completed"}

    async def test_invalid_status_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.step_update", {
            "plan_id": "p1", "step_id": "s1", "status": "unknown",
        })
        assert result.outcome == "denied"

    async def test_missing_plan_id_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.step_update", {
            "step_id": "s1", "status": "started",
        })
        assert result.outcome == "denied"


# ---------------------------------------------------------------------------
# revise
# ---------------------------------------------------------------------------

class TestRevise:
    async def test_emits_plan_revised(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.revise", {
            "plan_id": "p1",
            "reason": "scope changed after retro",
            "added_steps": [
                {"step_id": "s_new", "description": "add safety tests"},
            ],
        })
        assert result.outcome == "success"
        assert "plan_revised" in _event_types(host)

    async def test_added_step_count_in_event(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.revise", {
            "plan_id": "p1",
            "reason": "found gap",
            "added_steps": [
                {"step_id": "x1", "description": "new step 1"},
                {"step_id": "x2", "description": "new step 2"},
            ],
        })
        ev = next(e for e in _events(host) if e["event_type"] == "plan_revised")
        assert ev["payload"]["added_step_count"] == 2

    async def test_reason_in_event(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.revise", {
            "plan_id": "p1",
            "reason": "scope changed",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "plan_revised")
        assert ev["payload"]["reason"] == "scope changed"

    async def test_no_added_steps_allowed(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.revise", {
            "plan_id": "p1",
            "reason": "minor adjustment",
        })
        assert result.outcome == "success"
        assert result.data["added_step_count"] == 0

    async def test_missing_reason_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.revise", {
            "plan_id": "p1",
        })
        assert result.outcome == "denied"


# ---------------------------------------------------------------------------
# reflect
# ---------------------------------------------------------------------------

class TestReflect:
    async def test_emits_started_and_completed(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "Tier 3 implementation",
            "content": "All three adapters built and tested successfully.",
        })
        assert result.outcome == "success"
        types = _event_types(host)
        assert "reflection_started" in types
        assert "reflection_completed" in types

    async def test_no_outcome_scored_without_score(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x",
            "content": "y",
        })
        assert "outcome_scored" not in _event_types(host)

    async def test_outcome_scored_emitted_when_score_provided(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "code quality",
            "content": "Adapter follows established patterns.",
            "score": 0.9,
            "rubric": "adherence to CHP adapter pattern",
            "evaluator": "model",
        })
        types = _event_types(host)
        assert "outcome_scored" in types

    async def test_outcome_scored_has_score_value(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x",
            "content": "y",
            "score": 0.75,
        })
        ev = next(e for e in _events(host) if e["event_type"] == "outcome_scored")
        assert ev["payload"]["score"] == pytest.approx(0.75)

    async def test_returns_scored_flag(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x", "content": "y", "score": 0.5,
        })
        assert result.data["scored"] is True

    async def test_returns_scored_false_when_no_score(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x", "content": "y",
        })
        assert result.data["scored"] is False

    async def test_missing_content_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x",
        })
        assert result.outcome == "denied"

    async def test_score_out_of_range_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x",
            "content": "y",
            "score": 1.5,
        })
        assert result.outcome == "denied"

    async def test_evidence_refs_accepted(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.planning.reflect", {
            "subject": "x",
            "content": "y",
            "score": 0.8,
            "evidence_refs": ["ev_001", "ev_002"],
        })
        assert result.outcome == "success"
