"""Tests for DelegationAdapter.

All tests are stateless — no subprocess or external backend required.
"""
from __future__ import annotations

import pytest
from chp_core import LocalCapabilityHost, register_adapter
from chp_core.store import SQLiteEvidenceStore

from chp_adapter_delegation import DelegationAdapter, DelegationConfig


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_host() -> LocalCapabilityHost:
    adapter = DelegationAdapter()
    host = LocalCapabilityHost(store=SQLiteEvidenceStore(":memory:"))
    register_adapter(host, adapter)
    return host


def _events(host: LocalCapabilityHost) -> list[dict]:
    return [e for e in host.store.all() if "capability_uri" not in e.get("payload", {})]


def _event_types(host: LocalCapabilityHost) -> list[str]:
    return [e["event_type"] for e in _events(host)]


# ---------------------------------------------------------------------------
# Capability registration
# ---------------------------------------------------------------------------

class TestRegistration:
    async def test_four_capabilities_registered(self):
        host = _make_host()
        keys = " ".join(host._capabilities.keys())
        assert "chp.adapters.delegation.create" in keys
        assert "chp.adapters.delegation.accept" in keys
        assert "chp.adapters.delegation.complete" in keys
        assert "chp.adapters.delegation.reject" in keys


# ---------------------------------------------------------------------------
# create
# ---------------------------------------------------------------------------

class TestCreate:
    async def test_success(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "chp-agent-worker",
            "work_parcel": "Build the safety adapter package",
        })
        assert result.outcome == "success"
        assert result.data["to_agent"] == "chp-agent-worker"

    async def test_autogenerated_delegation_id(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-a",
            "work_parcel": "do work",
        })
        assert result.data["delegation_id"].startswith("del_")

    async def test_explicit_delegation_id_preserved(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "delegation_id": "my-del-001",
            "to_agent": "agent-a",
            "work_parcel": "do work",
        })
        assert result.data["delegation_id"] == "my-del-001"

    async def test_emits_delegation_created(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-b",
            "work_parcel": "write tests",
        })
        assert "delegation_created" in _event_types(host)

    async def test_event_contains_to_agent(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-x",
            "work_parcel": "task description",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_created")
        assert ev["payload"]["to_agent"] == "agent-x"

    async def test_event_contains_criteria_count(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-b",
            "work_parcel": "write tests",
            "acceptance_criteria": ["all tests pass", "coverage >= 80%", "no type errors"],
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_created")
        assert ev["payload"]["criteria_count"] == 3

    async def test_work_parcel_in_event(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-x",
            "work_parcel": "build the widget",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_created")
        assert ev["payload"]["work_parcel"] == "build the widget"

    async def test_default_from_session(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-c",
            "work_parcel": "something",
        })
        assert result.data["from_session"] == "local"

    async def test_explicit_from_session(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "from_session": "session_abc",
            "to_agent": "agent-c",
            "work_parcel": "something",
        })
        assert result.data["from_session"] == "session_abc"

    async def test_context_ref_round_trips(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "a",
            "work_parcel": "w",
            "context_ref": "corr_xyz789",
        })
        assert result.data["context_ref"] == "corr_xyz789"

    async def test_missing_to_agent_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "work_parcel": "missing to_agent",
        })
        assert result.outcome == "denied"

    async def test_missing_work_parcel_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "agent-d",
        })
        assert result.outcome == "denied"

    async def test_unknown_field_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.create", {
            "to_agent": "a",
            "work_parcel": "w",
            "extra": "bad",
        })
        assert result.outcome == "denied"


# ---------------------------------------------------------------------------
# accept
# ---------------------------------------------------------------------------

class TestAccept:
    async def test_success(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.accept", {
            "delegation_id": "del_abc",
        })
        assert result.outcome == "success"
        assert result.data["status"] == "accepted"

    async def test_emits_delegation_accepted(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.accept", {
            "delegation_id": "del_abc",
            "to_agent": "agent-worker",
        })
        assert "delegation_accepted" in _event_types(host)

    async def test_event_contains_delegation_id(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.accept", {
            "delegation_id": "del_xyz",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_accepted")
        assert ev["payload"]["delegation_id"] == "del_xyz"

    async def test_missing_delegation_id_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.accept", {})
        assert result.outcome == "denied"


# ---------------------------------------------------------------------------
# complete
# ---------------------------------------------------------------------------

class TestComplete:
    async def test_success_without_outcome(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.complete", {
            "delegation_id": "del_abc",
        })
        assert result.outcome == "success"
        assert result.data["status"] == "completed"

    async def test_emits_delegation_completed(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.complete", {
            "delegation_id": "del_abc",
        })
        assert "delegation_completed" in _event_types(host)

    async def test_outcome_included_in_event_when_provided(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.complete", {
            "delegation_id": "del_abc",
            "outcome": {"score": 0.9, "rubric": "test coverage"},
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_completed")
        assert "outcome" in ev["payload"]
        assert ev["payload"]["outcome"]["score"] == pytest.approx(0.9)

    async def test_outcome_absent_when_not_provided(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.complete", {
            "delegation_id": "del_abc",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_completed")
        assert "outcome" not in ev["payload"]

    async def test_missing_delegation_id_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.complete", {})
        assert result.outcome == "denied"


# ---------------------------------------------------------------------------
# reject
# ---------------------------------------------------------------------------

class TestReject:
    async def test_success(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.reject", {
            "delegation_id": "del_abc",
            "reason": "agent lacks required capabilities",
        })
        assert result.outcome == "success"
        assert result.data["status"] == "rejected"

    async def test_emits_delegation_rejected(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.reject", {
            "delegation_id": "del_abc",
            "reason": "out of scope",
        })
        assert "delegation_rejected" in _event_types(host)

    async def test_reason_in_event(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.reject", {
            "delegation_id": "del_abc",
            "reason": "cannot complete within deadline",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_rejected")
        assert ev["payload"]["reason"] == "cannot complete within deadline"

    async def test_delegation_id_in_event(self):
        host = _make_host()
        await host.ainvoke("chp.adapters.delegation.reject", {
            "delegation_id": "del_999",
            "reason": "x",
        })
        ev = next(e for e in _events(host) if e["event_type"] == "delegation_rejected")
        assert ev["payload"]["delegation_id"] == "del_999"

    async def test_missing_reason_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.reject", {
            "delegation_id": "del_abc",
        })
        assert result.outcome == "denied"

    async def test_missing_delegation_id_denied(self):
        host = _make_host()
        result = await host.ainvoke("chp.adapters.delegation.reject", {
            "reason": "no id provided",
        })
        assert result.outcome == "denied"
