#!/usr/bin/env python3
"""Generate spec/reserved-names.md — the language-neutral reserved-names registry.

The authoritative reserved sets live in Python source (types.py, signing.py).
A non-Python implementer shouldn't have to parse Python: this emits one table
covering evidence-event families, denial codes, anchor types, and reserved
prefixes. Regenerate after changing any reserved set:

    python scripts/gen-reserved-names.py && git diff spec/reserved-names.md

`protocol_checks.check_alignment` guards that this file matches source.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "packages" / "python"))

from chp_core import types as T  # noqa: E402
from chp_core.types import DenialReason  # noqa: E402

ANCHOR_TYPES = {
    "domain": "Web-PKI root: the domain serves /.well-known/chp-identity over TLS (chp-v0.2.md §3.1)",
    "did": "Decentralized root: a did:key ed25519 identity countersigns the CHP key via SSHSIG (chp-v0.2.md §3.1)",
}

PREFIXES = {
    "`chp.*`": "capability ids reserved for the protocol/reference implementation (governance §5)",
    "`execution_*`": "core lifecycle evidence events (chp-v0.1.md §6)",
    "`host-identity-<host_id>`": "the correlation carrying a host's own identity/key-lifecycle evidence (chp-v0.2.md §3.2)",
    "`chp-host-anchor`": "the SSHSIG namespace for did-anchor countersignatures (chp-v0.2.md §3.1)",
}


def main() -> int:
    families = sorted(
        (name, getattr(T, name)) for name in dir(T)
        if name.endswith("_EVIDENCE_TYPES") and isinstance(getattr(T, name), (set, frozenset))
    )
    lines: list[str] = [
        "# CHP Reserved Names",
        "",
        "Generated by `scripts/gen-reserved-names.py` from the reference source",
        "(`types.py`, `signing.py`) — do not edit by hand. These names are",
        "**reserved**: an implementation MUST NOT redefine their meaning. Vendor",
        "extensions MUST be reverse-DNS namespaced (`com.acme.…`) — see",
        "[chp-governance-v0.2.md §5](chp-governance-v0.2.md).",
        "",
        "## Evidence event families",
        "",
        "| Family | Reserved event types |",
        "|---|---|",
    ]
    for name, members in families:
        lines.append(f"| `{name}` | " + ", ".join(f"`{m}`" for m in sorted(members)) + " |")
    lines += [
        "",
        "## Reserved denial codes",
        "",
        "Registered in `DenialReason.RESERVED_CODES`; trigger predicates + gate",
        "ordering are normative in [chp-invocation-pipeline.md](chp-invocation-pipeline.md).",
        "",
    ]
    lines += [f"- `{c}`" for c in sorted(DenialReason.RESERVED_CODES)]
    lines += ["", "## Anchor types (chp-v0.2.md §3.1)", ""]
    lines += [f"- `{k}` — {v}" for k, v in sorted(ANCHOR_TYPES.items())]
    lines += ["", "## Reserved prefixes / namespaces", ""]
    lines += [f"- {k} — {v}" for k, v in PREFIXES.items()]
    lines.append("")

    out = REPO / "spec" / "reserved-names.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(REPO)} ({len(families)} families, "
          f"{len(DenialReason.RESERVED_CODES)} denial codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
